### ISSUE TITLE
Worried. Are you still alive?

### ISSUE THREAD

**Issue by xtrasmal** [mprzytulski/phpstorm-phpspec#10]
Hi there,

it's awfully quiet on your side. Are you allright?

**Comment by toby-griffiths** [comment]
Great to see some caring for the amazing people that give us open source plugins like this.

I too, hope you're OK @xtrasmal

**Comment by ciaranmcnulty** [comment]
I saw him alive and well about a week ago :-)

**Comment by toby-griffiths** [comment]
Hurrah!

**Comment by xtrasmal** [comment]
@toby-griffiths @ciaranmcnulty Great to hear. 💃  yeah everything is fine here :) thanks
